POST http://localhost:8081/user/register
Content-Type: application/json

{
    "usuari_id": 1,
  "usuari_nom": "Josep",
  "usuari_dni": "Josep",
  "usuari_adreça": "Josep",
  "usuari_telefon": 987654321,
  "usuari_contacte_emergencia": 123456789,
  "usuari_imatge": "imatge.jpg",
  "usuari_contra": "123456"
}