POST http://localhost:8080/user/register
Content-Type: application/json

{
  "usuari_id": 0,
  "usuari_nom": "Usuari prova",
  "usuari_dni": "12345678Y",
  "usuari_adreça": "",
  "usuari_telefon": 0,
  "usuari_contacte_emergencia": 0,
  "usuari_imatge": "",
  "usuari_contra": "123456"
}

