POST http://localhost:8080/user/register
Content-Type: application/json

{
  "usuari_id": 0,
  "usuari_nom": "Usuari prova",
  "usuari_dni": "12345678J",
  "usuari_adreça": "",
  "usuari_telefon": 0,
  "usuari_contacte_emergencia": 0,
  "usuari_imatge": "",
  "usuari_contra": "123456"
}

###
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "usuari_id": 0,
  "usuari_nom": "Usuari prova",
  "usuari_dni": "12345678Y",
  "usuari_adreça": "",
  "usuari_telefon": 0,
  "usuari_contacte_emergencia": 0,
  "usuari_imatge": "",
  "usuari_contra": "123456"
}

###
GET http://localhost:8080/usuaris/23
Content-Type: application/json


###
PUT http://localhost:8080/usuaris/23
Content-Type: application/json

{
  "usuari_id": 23,
  "usuari_nom": "Jordi",
  "usuari_dni": "12345678C",
  "usuari_adreça": "",
  "usuari_telefon": 0,
  "usuari_contacte_emergencia": 0,
  "usuari_imatge": "",
  "usuari_contra": "123456"
}

###
DELETE http://localhost:8080/usuaris/34
Content-Type: application/json


